version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017
    networks:
      - mongo_net
    volumes:
      - mongodb_data_container:/data

  mongo_express_client_container:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_container
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      #ME_CONFIG_BASICAUTH_USERNAME: admin
      #ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb_container
    networks:
      - mongo_net

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    volumes:
      - hasura_db_data:/var/lib/postgresql/data
    ports:
      - 65432:5432
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.7
    container_name: hasura
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - mongo_net
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - mongo_net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    container_name: logstash
    environment:
      - LOGSTASH_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - LOGSTASH_JDBC_DRIVER=org.postgresql.Driver
      - LOGSTASH_JDBC_DRIVER_JAR_LOCATION=/usr/share/logstash/logstash-core/lib/jars/postgresql.jar
      - LOGSTASH_JDBC_USERNAME=postgres
      - LOGSTASH_JDBC_PASSWORD=postgrespassword
      - LOGSTASH_ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./postgres-jdbc-input.conf:/usr/share/logstash/pipeline/logstash.conf
    #command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - 9600:9600
      - 5044:5044
    networks:
      - mongo_net
    depends_on:
      - elasticsearch
      - kibana
      - postgres


volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  hasura_db_data:
  mongodb_data_container:

networks:
  mongo_net:
    driver: bridge